[package]
name = "hexview"
version = "1.2.4"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
strip = "debuginfo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
